services:
  Order_master:
    container_name: order_master
    build:
        context:  /order_service
        dockerfile: Dockerfile
        secrets:
          - gh_token
    network_mode: host
    environment:
        TZ : America/New_York  # Set the timezone
        
  Market_data_master:
    container_name: mkt_data_master
    build:
        context:  /market_data_service
        dockerfile: Dockerfile
        secrets:
          - gh_token
    network_mode: host
    environment:
        TZ : America/New_York  # Set the timezone

secrets:
  gh_token:
    file: ./gh_token.txt  # The local file where your PAT is stored